package net.jonstef.mileage.jdbi;

import net.jonstef.mileage.api.Fillup;
import net.jonstef.mileage.api.Vehicle;
import org.skife.jdbi.v2.sqlobject.*;
import org.skife.jdbi.v2.sqlobject.customizers.RegisterMapper;

import java.util.List;

/**
 *
 */
public interface FillupDAO extends AutoCloseable {

	@SqlUpdate("create table if not exists fillup (\n" +
			"\tid bigint generated by default as identity,\n" +
			"\tdate timestamp,\n" +
			"\tmileage integer not null check (mileage>=1 AND mileage<=500000),\n" +
			"\tquantity decimal(19,2) not null,\n" +
			"\tvehicle varchar(255),\n" +
			"\tprimary key (id),\n" +
			"\tunique (mileage, vehicle)\n" +
			")")
	void createTable();

	@SqlUpdate("insert into fillup(date, mileage, quantity, vehicle) values (:date, :mileage, :quantity, :vehicle)")
	@GetGeneratedKeys
	long insert(@BindBean Fillup fillup);

	@SqlQuery("select id, date, mileage, quantity, vehicle from fillup where id = :id")
	Fillup findById(@Bind("id") Long id);

	@SqlUpdate("delete from fillup where id = :id")
	int deleteById(@Bind("id") Long id);

	@SqlQuery("select id, date, mileage, quantity, vehicle from fillup where vehicle = :vehicle order by date desc limit 0,:limit")
	List<Fillup> getFillups(@Bind("vehicle") String vehicle, @Bind("limit") int limit);

	@Override
	void close();

}
